export {dataAfterPriceRange} from "./dataAfterPriceRange"
export {filterByDiscount} from "./filterByDiscount"
// export {filterByMen} from "./filterByGender"
export {filterByGender} from "./filterByGender"
export {filterByPrice} from "./filterByPrice"
export {filterByRating} from "./filterByRating"
export {filterBySeason} from "./filterBySeason"
// export {filterBySummer} from "./filterBySeason"
export {filterBySearch} from "./filterBySearch"